### ISSUE TITLE
feat: Consider adding motion (.mtn) cache / 考虑加上动作缓存

### ISSUE THREAD

**Issue by CDog34** [xiazeyu/live2d-widget.js#4]
### Expected behavior 预期行为

Network request should only be make when requiring a certain .mtn file for the first time. And the same file should be loaded from cache for subsequent requests.
当且仅当第一次请求某个动作文件时发出网络请求。后续对同一个文件的请求应该从缓存中获取。

### Actual behavior 实际行为

Network requests are made each time requiring the same .mtn file.
请求同一个 .mtn 文件会发送多个网络请求。
![default](https://user-images.githubusercontent.com/11211603/36633654-5c8b9276-19d4-11e8-816a-6cc1819fb7ae.PNG)

### Steps to reproduce the behavior 复现步骤
config / 配置如下：
```yaml
live2d:
  enable: true
  scriptFrom: local
  model:
    use: local-model
  display:
    position: right
    width: 125
    height: 250
    hOffset: 50
  mobile:
    show: false
  react:
    opacityDefault: 1
```

P.S.  Actually, I'm using the `hexo-helper-live2d` plugin. But, I think it should be a issue for this repo. / 实际上，我是用的是 `hexo-helper-live2d` 插件，但是我认为这应该是这个仓库的模块的问题。

- [x] I have alreday read instructions in [CONTRIBUTING](./CONTRIBUTING.md). 
我已仔细阅读[CONTRIBUTING](./CONTRIBUTING.md)中的相关内容。

@EYHN @xiazeyu
